### ISSUE TITLE
Since Companion 3.3.1 pjlink goes into Error state after a while

### ISSUE THREAD

**Issue by tpk001** [bitfocus/companion-module-pjlink#86]
Since Companion 3.3.1 the pjlink module goes into error state within few days.
Haven't had time to diagnose.
Suspecting that the module not recover from error state. Can be related to the last 2 version updates.

Epson EB-L615U

**Comment by me2751** [comment]
We've also had problems since the last update. Restarting the module seems to fix it but that's not a long term solution. 

Our projector is a Digital Projection E-Vision lazer 10k.

**Comment by istnv** [comment]
I can't reproduce the problem.
If someone could start the debug log for the module (click on the '>_') and upload the log when that happens, I may be able to determine what is happening.

**Comment by istnv** [comment]
This may be related to the projector periodically resetting the password token.
The module has been updated to recognize this.
Re-open if still an issue.

**Comment by ntbutler87** [comment]
Hi there!
I've been experiencing this issue for a little while but have been ignoring it mostly until now. I'm on the latest version of Companion and of this module as of April '26, but it has been an issue over the last year or so since starting with Companion, connecting with our Sony vpl-phz10.
The connection is usually stable for a while, but then we see "error: Projector Disconnected" in the logs and we have to usually stop and re-start the connection to recover:
```log
info: Authorizing
system: Status: ok - Auth 0K
debug: disconnecting per protocol defintion : ( 
system: Status: connecting - Authorizing info: Authorizing
system: Status: ok - Auth OK error: Projector Disconnected
system: Status: undefined - Disconnected debug: Disconnected
system: Status: connection_failure
- Retrying connection
system: Status: connecting Authorizing info: Authorizing
system: Status: ok - Auth OK error: Projector Disconnected
system: Status: undefined - Disconnected debug: Disconnected
system: Status: connection_failure
- Retrying connection
system: Status: connecting Authorizing info: Authorizing
system: Status: ok - Auth OK error: Projector Disconnected
```

### 2 questions:
1. Is anyone else experiencing this issue at all still since the commit 1cc4d6efb238e0615704ca50582abd3173dbb37e? Again - it's not a big issue, but that fix doesn't seem to have fixed this symptom for my case.
2. Has there been any thought to a 'keep-alive' request being sent? I had a look at a PDF of the spec, and whilst there is no such command in the spec, the spec does appear to indicate that the connection would remain alive for 30sec from the last request, so my thinking would be something like sending the SNUM ? command as a relatively mundane/quick request every 25sec would keep the connection alive?

Cheers

**Comment by istnv** [comment]
Is there any other control program talking to the projector? 
This usually does not occur unless there is more than one remote trying to talk to the projector.

**Comment by ntbutler87** [comment]
@istnv none that I am aware of - it's a pretty small/basic setup and to my knowledge there isn't any others (particularly not using pjlink), but I will check with the two other people that would know if there is anything else configured. I recently forced authentication for pjlink on that projector and didn't tell anyone, so I don't think there'd be anyone else configuring another controller without knowing that password...
